version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: VirtualAssistance_UserServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kigali45
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d VirtualAssistance_UserServiceDb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  user-management:
    build: .
    container_name: user-management
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy   # âœ… waits until DB is ready
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
